### ISSUE TITLE
UUID has some interaction with mock_model

### ISSUE THREAD

**Issue by canyon289** [aivillage/llm_router#8]
`UUID 1` works but not `UUID 1234`

![image](https://github.com/aivillage/llm_router/assets/7213793/6f935b01-baa4-4965-b1d8-d809f12e256f)

![image](https://github.com/aivillage/llm_router/assets/7213793/3055dba8-8545-4c8a-be68-e53fd6d7c36d)

**Comment by canyon289** [comment]
Seems to be fine now

**Comment by canyon289** [comment]
Now there is some other behavior that depending on the UUID a different response is returned. Need to check if this is just an issue with the mock model or there's some other bug

![image](https://github.com/aivillage/llm_router/assets/7213793/2afdd047-b46c-49ea-b757-74923d0d8ad5)
![image](https://github.com/aivillage/llm_router/assets/7213793/008d4e3d-c4f3-4e60-82af-240883d658e1)

**Comment by comath** [comment]
The UUIDs are stored in redis and just looked up. If you pass an existing UUID it'll just grab that old one. It's meant to be an actual cryptographically random UUID and the security relies on the client using a proper implementation. 

A configurable TTL would ameliorate this in testing. It's currently fixed at an hour: https://github.com/aivillage/llm_router/blob/main/src/chat/state.rs#L105\

**Comment by canyon289** [comment]
Cool, closing this
